### ISSUE TITLE
连续缩进情况下有可能缺少缩进层级的问题

### ISSUE THREAD

**Issue by SigureMo** [megemini/convert_doctest#2]
复现方式：

```bash
convert-doctest python/paddle/jit/api.py
```

具体函数：

load https://github.com/PaddlePaddle/Paddle/blob/5b8f06377cd1199b6f9c96e7289bced90a9740c1/python/paddle/jit/api.py#L1275

<img width="808" alt="image" src="https://github.com/megemini/convert_doctest/assets/38436475/f4ff47cb-43e0-4814-bab5-fdf48e4dd913">

@megemini

**Comment by megemini** [comment]
`.. code-block:: python` 的缩进导致后续依赖判断错误，已经修改～

当时写的比较匆忙，谢拉！：）
