### ISSUE TITLE
非目录中的文件会报错

### ISSUE THREAD

**Issue by SigureMo** [megemini/convert_doctest#5]
比如当前目录下的 ttt.py，因为 `file_path.rsplit('/', 1)` 只有一个元素而报错～

<img width="718" alt="image" src="https://github.com/megemini/convert_doctest/assets/38436475/c195da58-b110-49cb-9b90-01dd58af2059">

**Comment by megemini** [comment]
这个版本有点老 更新一下再试试 ～ 🫣

**Comment by SigureMo** [comment]
嗯嗯，更新后没问题了
